import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="card">
          <div>
            <h2 className="card-title">To Do App</h2>
            <div className="input-group">
              <input type="text" name="todo task" className="todo-input" />
              <input type="button" value="+" className="todo-submit" />
            </div>
            <ul className="todo-list">
              <li>1</li>
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}
